FROM golang:1.22 as build_service
ENV CGO_ENABLED=0
ARG BUILD_REF

WORKDIR /service

COPY . .

RUN go build -ldflags "-X main.build=${BUILD_REF}" -o service

RUN ls -l /service

FROM alpine:3.14
ARG BUILD_DATE
ARG BUILD_REF

COPY --from=build_service /service/service /service/service

WORKDIR /service

CMD ["./service"]

LABEL org.opencontainers.image.created="${BUILD_DATE}" \
    org.opencontainers.image.title="First App Title" \
    org.opencontainers.image.author="Turan" \
    org.opencontainers.image.revision="${BUILD_REF}" 